version: "3.9"

services:
  redis:
    image: redis:7.4.0-alpine
    expose:
      - 6379

  backend-api:
    depends_on:
      - redis
      - postgres
    expose:
      - 8080
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/code
      - /app/node_modules
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload --proxy-headers

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app
    expose:
      - 3000
    command: npm start

  celery_worker:
    container_name: celery_worker
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery --app app.celery.worker worker --loglevel=info --uid=nobody  --gid=nogroup
    volumes:
      - ./backend/:/code
    depends_on:
      - backend-api
      - redis

  flower:
    container_name: flower
    expose:
      - 5555
    environment:
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_RESULT_BACKEND=redis://redis/0
    depends_on:
      - backend-api
      - celery_worker
      - redis
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery --broker=redis://redis/0 flower --port=5555 --url-prefix=/flower

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/nginx/certs/server.crt:/etc/nginx/server.crt
      - ./proxy/nginx/certs/server.key:/etc/nginx/server.key
    depends_on:
      - backend-api
      - flower
    ports:
      - "80:80"
      - "443:443"

  postgres:
    image: postgres:16.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    expose:
      - 80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8086
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  mailhog:
    image: mailhog/mailhog:latest
    expose:
      - 8025
    ports:
      - "1025:1025"


volumes:
  postgres_data:
  pgadmin_data: