version: "3.9"

services:
  redis:
    image: redis:7.4.0-alpine
    expose:
      - ${REDIS_PORT_INTERNAL}

  backend-api:
    depends_on:
      - redis
      - postgres
    expose:
      - ${BACKEND_PORT_INTERNAL}
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - REDIS_PORT=${REDIS_PORT_INTERNAL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - PROJECT_NAME=${PROJECT_NAME}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DEBUG=${BACKEND_DEBUG}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - DOMAIN=${DOMAIN}
      - ACCESS_TOKEN_EXPIRE_SECONDS=${ACCESS_TOKEN_EXPIRE_SECONDS}
      - REFRESH_TOKEN_EXPIRE_SECONDS=${REFRESH_TOKEN_EXPIRE_SECONDS}
      - VERIFY_MAIL_PATH=${VERIFY_MAIL_PATH}
      - PASSWORD_RESET_PATH=${PASSWORD_RESET_PATH}
      - POSTGRES_TEST_DB=${POSTGRES_TEST_DB}
    volumes:
      - ./backend/:/code
    entrypoint: ../docker-entrypoint.sh
    command: uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT_INTERNAL} --reload --proxy-headers

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app
    expose:
      - ${FRONTEND_PORT_INTERNAL}
    environment:
      - DEBUG=${FRONTEND_DEBUG}
      - FAST_REFRESH=${FAST_REFRESH}
      - REACT_APP_DOMAIN=${DOMAIN}
      - REACT_APP_VERIFY_MAIL_PATH=${VERIFY_MAIL_PATH}
      - REACT_APP_PASSWORD_RESET_PATH=${PASSWORD_RESET_PATH}
#    command: npm start -FAST_REFRESH=${FAST_REFRESH} -REACT_APP_DOMAIN=${DOMAIN} -REACT_APP_VERIFY_MAIL_PATH=${VERIFY_MAIL_PATH} -REACT_APP_PASSWORD_RESET_PATH=${PASSWORD_RESET_PATH}
    command: |
      npm start -FAST_REFRESH=${FAST_REFRESH} -REACT_APP_DOMAIN=${DOMAIN} \
      -REACT_APP_VERIFY_MAIL_PATH=${VERIFY_MAIL_PATH} \
      -REACT_APP_PASSWORD_RESET_PATH=${PASSWORD_RESET_PATH}


  celery_worker:
    container_name: celery_worker
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery --app app.celery.worker worker --loglevel=info --uid=nobody  --gid=nogroup
    volumes:
      - ./backend/:/code
    depends_on:
      - backend-api
      - redis

  flower:
    container_name: flower
    expose:
      - ${FLOWER_PORT_INTERNAL}
    environment:
      - CELERY_BROKER_URL=redis://redis:${REDIS_PORT_INTERNAL}/0
      - CELERY_RESULT_BACKEND=redis://redis:${REDIS_PORT_INTERNAL}/0
    depends_on:
      - backend-api
      - celery_worker
      - redis
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery --broker=redis://redis:${REDIS_PORT_INTERNAL}/0 flower --port=${FLOWER_PORT_INTERNAL} --url-prefix=/flower

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/nginx/certs/server.crt:/etc/nginx/server.crt
      - ./proxy/nginx/certs/server.key:/etc/nginx/server.key
    depends_on:
      - backend-api
      - flower
      - frontend
    environment:
      - BACKEND_PORT_INTERNAL=${BACKEND_PORT_INTERNAL}
      - FRONTEND_PORT_INTERNAL=${FRONTEND_PORT_INTERNAL}
      - FLOWER_PORT_INTERNAL=${FLOWER_PORT_INTERNAL}
      - PGADMIN_PORT_INTERNAL=${PGADMIN_PORT_INTERNAL}
      - MAILHOG_UI_PORT_INTERNAL=${MAILHOG_UI_PORT_INTERNAL}
    ports:
      - "80:80"
      - "443:443"

  postgres:
    image: postgres:16.4-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT_INTERNAL}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    expose:
      - ${PGADMIN_PORT_INTERNAL}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT_INTERNAL}
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  mailhog:
    image: mailhog/mailhog:latest
    expose:
      - ${MAILHOG_UI_PORT_INTERNAL}
    ports:
      - ${MAILHOG_PORT}:${MAILHOG_PORT_INTERNAL}


volumes:
  postgres_data:
  pgadmin_data: