"""tasks modified

Revision ID: 5ed2a576ffc9
Revises: e34236c50348
Create Date: 2024-10-18 18:31:00.509259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed2a576ffc9'
down_revision: Union[str, None] = 'e34236c50348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.drop_column('tasks', 'is_finished')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_finished', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###
